// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxnlmbhnxzrwibghgzzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4bmxtYmhueHpyd2liZ2hnenpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjA2ODIsImV4cCI6MjA2NTAzNjY4Mn0.jXfVaU43uHBKUCG2n6lke5eN8OoshGACCg-U2BzBHzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);